name: InLaw
description: InLaw the lawyer and clients app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  localization: ^2.1.0
  flutter_svg: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mask_text_input_formatter: ^2.1.0
  dio: ^4.0.6
  lottie: ^1.2.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.4
  material: ^1.0.0+2
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.8.0
  flutter_neumorphic: ^3.0.0

flutter_native_splash:
  image: lib/assets/images/splashScreen.png
  color: "#011C2E"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

flutter_icons:
  image_path: "lib/assets/images/foregroundLogo.png"
  ios: true
  android: true
  adaptive_icon_background: "#011C2E"
  adaptative_icon_foreground: "lib/assets/images/foregroundLogo.png"
  remove_aplha_ios: true

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/animations/

  fonts:
    - family: Kanit
      fonts:
        - asset: lib/assets/fonts/Kanit-Regular.ttf
